[project]
name = "cart-pole"
version = "0.1.0"
description = "cart-pole-ppo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.0",
    "gymnasium>=0.29.1",
    "torch>=2.6.0",
    "tensordict>=0.3.0",
    "torchrl>=0.3.0"
]
